/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p sapdblib_interface.h: ..\SAPDBLib\sapdblib.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SAPDBLIB_INTERFACE_H
#define SAPDBLIB_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface local.SAPDBLib
 */
class LocalSAPDBLibInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.SAPDBLib"; }

public:
    LocalSAPDBLibInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LocalSAPDBLibInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

namespace local {
  typedef ::LocalSAPDBLibInterface SAPDBLib;
}
#endif
