/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a sap_adapt sapwindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SAP_ADAPT_H
#define SAP_ADAPT_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.SapWindow
 */
class SapWindowAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.SapWindow")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.SapWindow\">\n"
"    <method name=\"SendAutrgNrRecive\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"in_iAuftrNr\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SapWindowAdaptor(QObject *parent);
    virtual ~SapWindowAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString SendAutrgNrRecive(int &in_iAuftrNr);
Q_SIGNALS: // SIGNALS
};

#endif
