/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a sap_adapt sapwindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "sap_adapt.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SapWindowAdaptor
 */

SapWindowAdaptor::SapWindowAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SapWindowAdaptor::~SapWindowAdaptor()
{
    // destructor
}

QString SapWindowAdaptor::SendAutrgNrRecive(int &in_iAuftrNr)
{
    // handle method call local.SapWindow.SendAutrgNrRecive
    //return static_cast<YourObjectType *>(parent())->SendAutrgNrRecive(in_iAuftrNr);
}

